language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: akuhyG586V5udyYSOW5YCVsfkcKKXLsNOSjx2JJca4l+Uu3HVDWpq3t6LFvydlZzYqm8geORn/MeWpMoJiRoD6RQHQsLx1L9Tap+tTgwLnEIaeV7rFYumi2H71NDpIkkJ8BN9xRyszh+0TMzgkEIYk3ZbdYHRfXd1Mljh7Ypi2thGyL6rh3CrYVrILqRe2GjO11q7WnFKOlk1bBv9zdTQ+dzEfNjLHD/UakQ8z+ya5DJ5Bb2pfZxBsQ6gyTNeKz/rwUpattuWFAZt2yIMQCNv8DC0/HbxXJLMWp1zPGENVTresR9HmquRtEtZ7wD+9T/P1P4cJeJh6rzaUJgC95fLkerApZQX4L/+tm7F5qMbe5fwYD/pJXqb04K42Xcqz+rc7qtB2CgEH2KOqPuGMX4wacltrinMSYTlJgDkFRvWeUky8m2TmNeL4D/bwAxM9aDx/FmpGvbNjC4mKwusrm5bXoGrqXSLVhmuQ0TJtMUPtOuy3kF+zovt6GzouKtgvLzy98/+v/FsCUDArDycBGou0RyDAljyrXMlJ6/bbScITPe/8Bi63/QK86Kb62BhIbGa5ccZ0wNL41whk4TceYNbJM81PFaZ3oHfj13yZZc2YbfZYVuhfoKzMGLPe5gwYJHgfg598i0uiXItUWApEs7SsrIg/Y/GEYMLCNU1kYliCg=
  app: project-1-36
  on:
    repo: uva-cs3240-f20/project-1-36
