language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: PxntTInJXCqAtvfnSph+se1RAfNI14mt1bgMLZFePlyhvV3dlaj/qAr6RtxCAZds1FlcGr/v8aKO9CQt9trWhec32Ami3dQb5nyERbe9rTbcENG45QFWM+fwzg6NjOD46tSFSnv/v0jdBp/ui59v4kIs1O4cnBEVsaW6HBN7TydySPLkw0OlIrbybezUHPM88DplmzLiyMBBBBAaONq8yQcAPS4kWs4lzNEop9EKqU6d1AC3egMQwJSXamUfTLur7Kvg/dXe2RxYEINly7AATUXwebpji7FwmOHHnNrL3a26jXTyU8NoHeRVC9HZTzI6oflhzWrzfptdibCev29QizJ0ehys9AWajyuXSwFDJMx89thkT2JI3qzMxJFzGwMnQkX+sz+uidb6j0NicDtlKDOfhR81zv5qJjN5KUAlemwLQE4J9V/VSvuJEUojZaUXlStvGB10Z4utDA7mAO8K3c+Csy7PqGjAFISF/a3wnIFDVCcmRIYS+fuOVWEZa0kMcmEBBru4hEdxYW3p/99V4JhGV8yhiID4i75mDt4axST8RZOHKjqKZJv4ljm23WJi352p+wGsl1Y2RqilmaBYRID8Q6xbjzqlkHlikJMfq1SzitXRx6mo5mjYyk/KxVasJGexd6Z2Z8CPxcDG7dfHCYLmiISPGDfVJOpQ8HczOIo=
  app: donationapp
  on:
    repo: uva-cs3240-f20/project-1-36
