language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: ugRBZWWySNgK6FJ/s943Cuym9XhyJ8l6w1t+Pj6pgxQMiDTNxf6odF2Bfn3boF19V4G11J0MhbVCvf135R5rncLpln91SN4b7KeS4PbPZPv+ktCX8RUXksC7I5b0eSHVS3uV00L+23OIb4H21oIPfv3ikQL/hFrtLjhgxtGOyEfbTC5pPHGP1YDI2bW4fPXnGU17gyLpJiteT24IuilJ32FffEZGp5Zd/oFvg9CaDTueJ7syWApkYBvMReL/ozYWwFq/mMDtkqJFFpSkbCGtgvAFjzPLa+SdXKrz+Y0+Ak5EErvzMQ0ekXtat8bEoQRWsm87SyttTzN7J9WUXb6LkRkhjGogP8O/Do385zu1o0BAeIsmyWpta3/12gBnFkAE/9J8mEawInMVj1PwwliAQHeFtJda+cMgj4FHoWH8wUkRxqsUNQza1mH/ZWGjyksKPIAtNPth3/X3DFs9VHmYOavAgZ9ha3OgtKqKw85BrgGmy5dny1VCcow5w1J3oMNbz48pDcqoBR3ij9SOzDHI/1BM5jD4MClkyYWxxm6WzW5sqoFHwDkDt+oyj38tOu5QwTWI6b+TrFkq5C5wRGGRfUK7fQdKHd9RkFLN43SL3Nr5ixPYO7guy7gEFwErP0VLD0Az1Bif+BPclyY5af5DwlL/nRUUig6BQ8sqQ4T9e8A=
  app: project-1-36
  on:
    repo: uva-cs3240-f20/project-1-36
