language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: hC0iRcpD+5fsIMnXGO9tP5wPfUoA3zWVwlD206R4V/zufyXKscAEuJKlz0iXhWlqdqnerzZ3a2TCrGrHv2VTvWdWrZVn2zOBQ2acpV2bVGwsBi2rCqpc1n6hCVM/Ad0aWJt3NZtbi/T5weCztxfn5Z5HXVtc4YmI+ePY4ckaq2wWdxCvLufvovtFRrxHFW7dPRTcCPdXwL4Ynb9NlA90cZfCmQqloswBAKbtIDRa7ZidMtBVcMl5cW8hLlysLbAkuc9w6byuBCayXXBMSWTrbaWlqme4NCF/VpRem2K6w6T6jvIGFLHB5xjPbJjfenzGIRhp3EF1qUImJjc42Lno5ViTVxkcCEGR4qjWWp+nhLlYPHlfeU5vRZsDLpaUGjCt1IIax/FvMbn8l9ao1pOfSlcQJqoBLZhLK5rTrC8CEB/1qkC09EUzF8DxFuR5ayGRvwOe4pdDXWB5G7AnSBj/uqfB2EiGLaToL4CCJ+0D36ojI0KYRiW2WCp/ZgHvjC5/hLymKp45IppGllT2xL3Wj1SaiivcgweYd7G16kM7oFUafoONIdKYp4L18CoTbEU+ggcuf5piEaWG8VrgtvEvpAeuJk04D2v1hIs3bDbFFTYhqHpBPdUeyN4LANv3RbhAO+kK+41a+a9jcvX6JxiWES7HpDfrFPq+TCIiy3cRYvk=
  app: website-1-36
  on:
    repo: uva-cs3240-f20/project-1-36
