# Generated by Django 3.1.1 on 2020-11-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_opp',
            name='date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
