# Generated by Django 3.1.1 on 2020-11-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0002_auto_20201115_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_opp',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
