# Generated by Django 3.1.2 on 2020-10-13 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('donationapp', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='causes',
            name='total_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
