# Generated by Django 3.1.1 on 2020-10-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0006_auto_20201015_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
