# Generated by Django 3.1.1 on 2020-10-18 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0008_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer_Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('total_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('people_needed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
