# Generated by Django 3.1.2 on 2020-10-23 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0009_volunteer_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_opportunity',
            name='people_needed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
