# Generated by Django 3.1.1 on 2020-11-06 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donationapp', '0010_auto_20201023_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_opportunity',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Volunteer_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donationapp.cause')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
