# Generated by Django 3.1.1 on 2020-11-06 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0011_auto_20201106_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer_Opp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('date', models.DateTimeField(null=True, verbose_name='date published')),
                ('total_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('people_needed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer_Opportunity',
        ),
    ]
