# Generated by Django 3.1.1 on 2020-11-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0012_auto_20201106_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_transaction',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donationapp.volunteer_opp'),
        ),
    ]
