# Generated by Django 3.1.1 on 2020-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0013_auto_20201106_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_opp',
            name='begin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='volunteer_opp',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteer_opp',
            name='date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
