# Generated by Django 3.1.1 on 2020-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0014_auto_20201106_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_opp',
            name='end',
            field=models.TimeField(null=True),
        ),
    ]
