# Generated by Django 3.1.1 on 2020-11-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0015_auto_20201106_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_opp',
            name='date',
        ),
    ]
