# Generated by Django 3.1.1 on 2020-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0016_remove_volunteer_opp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_opp',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
